server:
  port: 8080
spring:
  data:
    redis:
      repositories:
        enabled: true
  redis:
    database: 0
    host: localhost
    port: 6379
  session:
    store-type: redis
  datasource:
    username: root
    password: mysql-notebook
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:config/mybatis-config.xml